language: python
python:
  - "3.5"

# command to install dependencies
install:
- pip install coverage coveralls

# command to run tests
script:
- python -m unittest discover -p "*Test.py" -v
# run coverage if tests success
- coverage run --source=grammpy -m unittest discover -s tests -p "*Test.py" -q

# run coverage if tests success
after_sucess:
- coveralls
- coverage report -m

# disable email notifications
notifications:
  email: false