language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

# command to install dependencies
install:
- pip install coverage python-coveralls

# command to run tests with coverage
script:
- coverage run --source=grammpy -m unittest discover -s tests -p "*Test.py" -q

# report coverage
after_script:
- coverage report -m
- coveralls

# disable email notifications
notifications:
  email: false
